#!/usr/bin/env python3
"""Builds Source/Data/latin-words.txt for the P1 zh/en mixed-typing feature
(see ~/.claude/plans/zhuyin-ime-personal.md's "P1 設計" section and
Source/Engine/MixedScript/latin_lexicon.h).

Source: macOS's bundled BSD word list (/usr/share/dict/words -- see
ACKNOWLEDGEMENTS.md for its license). Filtering:
  - keep only lines that are entirely lowercase ASCII letters (a-z); this
    both excludes proper nouns (the BSD list capitalizes them) and excludes
    apostrophe'd contractions/possessives, matching the standard-layout
    Bopomofo key set MixedScriptTracker operates on (letters only).
  - length 2-15 (2: MixedScriptTracker::kMinAmbiguousWordLength never
    considers shorter runs anyway; 15: matches ReadingGrid's own
    kMaximumSpanLength-adjacent scale and rules out the word list's long
    tail of compounds/technical Latin that are vanishingly unlikely to be
    typed as a Bopomofo-mode English run).

The output is written in sorted order, and that is load-bearing, not
cosmetic: LatinLexicon keeps its isPrefix() index ordered as the file
loads, which is a linear merge for a pre-sorted file and a full sort
otherwise. Emitting an unsorted list still works, it just moves ~200k
words' worth of sorting into the load.

No frequency/rank data is written -- this repo did not have a
license-clear (MIT/CC0/public-domain) frequency-ranked English word list
available to verify at the time this was built (per the P1 spec's
constraint: only use one if its source and license can be recorded in
ACKNOWLEDGEMENTS.md). LatinLexicon.loadBuiltinWordList() assigns ranks by
file order when none is given, which is *not* a real frequency signal;
Source/Data/latin-tech-seed.txt's hand-picked, explicitly-ranked terms are
what P1 actually relies on for the words that matter (see BASELINE.md's
26%-ambiguous list). Revisit if/when a verified frequency list is sourced
for P2's re-ranking work.

Usage:
    python3 tools/lexicon/build_lexicon.py \
        --source /usr/share/dict/words \
        --output Source/Data/latin-words.txt
"""

import argparse
import pathlib
import re
import sys

LOWERCASE_WORD_RE = re.compile(r"^[a-z]+$")


def build(source: pathlib.Path, output: pathlib.Path, min_len: int, max_len: int) -> int:
    words = set()
    with source.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            word = line.strip()
            if not word:
                continue
            if not LOWERCASE_WORD_RE.match(word):
                continue
            if not (min_len <= len(word) <= max_len):
                continue
            words.add(word)

    sorted_words = sorted(words)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as f:
        f.write(
            "# Generated by tools/lexicon/build_lexicon.py from "
            f"{source} ({len(sorted_words)} words). Do not hand-edit;\n"
            "# see that script's docstring for filtering rules and\n"
            "# ACKNOWLEDGEMENTS.md for the source list's license.\n"
        )
        for word in sorted_words:
            f.write(word + "\n")
    return len(sorted_words)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=pathlib.Path, default=pathlib.Path("/usr/share/dict/words"))
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parents[2] / "Source" / "Data" / "latin-words.txt",
    )
    parser.add_argument("--min-len", type=int, default=2)
    parser.add_argument("--max-len", type=int, default=15)
    args = parser.parse_args()

    if not args.source.exists():
        print(f"error: source word list not found: {args.source}", file=sys.stderr)
        return 1

    count = build(args.source, args.output, args.min_len, args.max_len)
    print(f"wrote {count} words to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
